version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1972
      - 52773
    volumes:
      - ./:/home/irisowner/dev
      - ./dur:/dur
    environment:
      - ISC_DATA_DIRECTORY=/dur/iris_conf.d
      - ISC_CPF_MERGE_FILE=/dur/merge/merge.cpf
