services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1972
      - 52773
    volumes:
      - ./:/home/irisowner/dev
      - ../shared:/shared
    environment:
      - ISC_DATA_DIRECTORY=/shared/dur
    #   # - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
